---

- name: set hostname
  hostname: 
    name: "{{ inventory_hostname }}"

- name: set hostname in /etc/hosts 
  lineinfile:
    dest: "/etc/hosts"
    regexp: '^127.0.0.1\s*{{ inventory_hostname }}'
    line: "127.0.0.1 {{ inventory_hostname }}"
    state: present

- name: set host in /etc/hosts 
  lineinfile:
    dest: "/etc/hosts"
    regexp: '^{{ ansible_default_ipv4.address }}\s*{{ inventory_hostname }}'
    line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }}"
    state: present
  when: ansible_default_ipv4 is defined
